version: '3.8'
services:
  spark-master:
    build:
      context: .
      dockerfile: spark_Dockerfile  # Spark 전용 Dockerfile
    container_name: anovelgen-spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./data:/data  # 데이터 공유
      - ./workspace/spark:/spark  # Spark 작업 디렉토리
    networks:
      - spark-net

  spark-worker:
    image: bitnami/spark:latest
    container_name: anovelgen-spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://anovelgen-spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-net

  pytorch-container:
    build:
      context: .
      dockerfile: pytorch_Dockerfile  # PyTorch 전용 Dockerfile
    container_name: anovelgen-pytorch-container
    volumes:
      - ./data/processed_data:/processed_data  # 전처리된 데이터만 마운트
      - ./workspace/pytorch:/pytorch  # PyTorch 작업 디렉토리
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
